name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build, lint and test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install depedencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run linting (flake8)
        run: |
          flake8 .
        
      - name: Run formatting (black)
        run: |
          black . --check --exclude .venv

      - name: Run tests
        run: |
          pytest
